In [2]:
import numpy as np

In [17]:
mat = np.eye(3,4,0)
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.random.randint(10, 20,3)

array([18, 16, 12])