In [7]:
import numpy as np

# Example 1D array
a = np.array([1, 2, 3, 4, 5])

# Convert to a column vector using np.newaxis
column_vector = a[:, np.newaxis]

print("Original 1D array:")
print(a)
print("Shape of original array:", a.shape)

print("\nColumn vector:")
print(column_vector)
print("Shape of column vector:", column_vector.shape)

# Adding a new axis to convert 1D array to a row vector
a_row = a[np.newaxis,:]
print("\nRow vector:\n", a_row)
print("Shape of row vector:", a_row.shape)

Original 1D array:
[1 2 3 4 5]
Shape of original array: (5,)

Column vector:
[[1]
 [2]
 [3]
 [4]
 [5]]
Shape of column vector: (5, 1)

Row vector:
 [[1 2 3 4 5]]
Shape of row vector: (1, 5)


In [9]:
import numpy as np

# Example 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Original 2D array (matrix):")
print(b)
print("Shape of original array:", b.shape)

# Insert a new axis at position 1 (rows) using np.newaxis
matrix_with_axis = b[np.newaxis,:,:]

print("\nMatrix with new axis at position 1 (rows):")
print(matrix_with_axis)
print("Shape of matrix with new axis at position 1:", matrix_with_axis.shape)

# Insert a new axis at position 2 (columns) using np.newaxis
matrix_with_axis_columns = b[:, np.newaxis, :]

print("\nMatrix with new axis at position 2 (columns):")
print(matrix_with_axis_columns)
print("Shape of matrix with new axis at position 2:", matrix_with_axis_columns.shape)

# Insert a new axis at the end (depth) using np.newaxis
matrix_with_axis_depth = b[:, :, np.newaxis]

print("\nMatrix with new axis at the end (depth):")
print(matrix_with_axis_depth)
print("Shape of matrix with new axis at the end:", matrix_with_axis_depth.shape)

Original 2D array (matrix):
[[1 2 3]
 [4 5 6]]
Shape of original array: (2, 3)

Matrix with new axis at position 1 (rows):
[[[1 2 3]
  [4 5 6]]]
Shape of matrix with new axis at position 1: (1, 2, 3)

Matrix with new axis at position 2 (columns):
[[[1 2 3]]

 [[4 5 6]]]
Shape of matrix with new axis at position 2: (2, 1, 3)

Matrix with new axis at the end (depth):
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
Shape of matrix with new axis at the end: (2, 3, 1)
